
server:
  port: 18000

spring:
  threadpool:
    thread-pool-core-size: 10
    thread-pool-max-size: 10
    thread-pool-keep-alive-seconds: 30
    thread-pool-queue-capacity: 10000
  #http rest
  rest:
    connection:
      connection-request-timeout: 20000
      max-per-route: 100
      max-total: 2700
      read-timeout: 60000
      connect-timeout: 5000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 10MB
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  application:
    name: ${parent.artifactId}
  profiles:
    active: tencent-sit
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  resources:
    static-locations: classpath:/static/,classpath:/views/
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates
#mybatisplus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      field-strategy: NOT_NULL
      id-type: ASSIGN_ID
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
# 项目本身配置。
project:
  # 认证
  auth:
    #无需token请求路径
    ignore:
      urls[0]: /commonbusinessGenerator/code

    endpoint:
      url: http://localhost:${server.port}
    token-store: jdbc
  #基础服务API地址
  remote:
    mc-path:
      send-msgcenter-sms-authcode: /authcode/sendmsg
